router id 10.0.3.1;
protocol device {}
protocol direct {
  ipv4;
}
protocol kernel {
  ipv4 { export all; import all; };
  learn;
}
protocol bgp bgp_as2 {
  local 172.30.23.3 as 65003;
  neighbor 172.30.23.2 as 65002;
  advertise hostname off;
  transport tls;
  tls certificate "/certs/router.crt";
  tls pkey "/certs/router.key";
  tls root ca "/certs/ca.crt";
  tls local sni "as3.bgpost.lab";
  tls peer sni "as2.bgpost.lab";
  ipv4 {
    import all;
    export all;
  };
}
protocol static {
  ipv4 { export all; };
  route 10.3.0.0/16 blackhole;
}