router id 2.2.2.2;

log stderr all;

protocol device {
}

protocol direct {
    ipv4;
}

protocol kernel {
    ipv4 {
        import all;
        export all;
    };
}

protocol bfd{
}

protocol ospf ospf1 {

    area 0 {

        interface "eth1" {
            hello 5;
        };

        interface "eth2" {
            hello 5;
        };

        interface "eth3" {
            hello 5;
        };

        interface "lo" {
            stub;
        };
    };
}

protocol bgp r9 {

    local as 65001;

    neighbor 10.0.29.3 as 65002;

    bfd yes;

    graceful restart yes;
    long lived graceful restart yes;



    ipv4 {
        import all;
        export all;
    };
}

protocol bgp r1 {

    local as 65001;

    neighbor 10.0.12.2 as 65001;

    graceful restart yes;
    long lived graceful restart yes;

    ipv4 {
        import all;
        export all;
        next hop self;
    };
}
