router id 5.5.5.5;

log stderr all;

protocol device {
}

protocol direct {
    ipv4;
}

protocol kernel {
    ipv4 {
        import all;
        export all;
    };
}

protocol ospf ospf1 {

    area 10 {
        nssa;

        interface "eth0" {
            hello 5;
        };

        interface "eth1" {
            hello 5;
        };

        interface "lo" {
                stub;
        };
    };
}
