router id 9.9.9.9;

log stderr all;

protocol device {
}

protocol direct {
    ipv4;
}

protocol kernel {
    ipv4 {
        import all;
        export all;
    };
}

protocol bfd{
}


protocol bgp r1 {

    local as 65002;

    neighbor 10.0.19.2 as 65001;

     bfd yes;

    graceful restart yes;
    long lived graceful restart yes;

    ipv4 {
        import all;
        export all;
    };
}

protocol bgp r2 {

    local as 65002;

    neighbor 10.0.29.2 as 65001;

    bfd yes;

    graceful restart yes;
    long lived graceful restart yes;

    ipv4 {
        import all;
        export all;
    };
}

protocol static {
    ipv4;
    route 100.100.100.0/24 blackhole;
}
