router id 4.4.4.4;

log stderr all;

protocol device {
}

protocol direct {
    ipv4;
}

protocol kernel {
    ipv4 {
        import all;
        export all;
    };
}

protocol ospf ospf1 {

    area 0 {

        interface "eth1" {
            hello 5;
        };

        interface "eth2" {
            hello 5;
        };

        interface "eth3" {
            hello 5;
        };

        interface "lo" {
            stub;
        };
    };

    area 20 {
        stub;

        interface "eth4" {
            hello 5;
        };

        interface "lo" {
            stub;
        };
    };
}
